#!/usr/bin/env Rscript

suppressPackageStartupMessages({
  library(readr)
  library(dplyr)
  library(fixest)
})

args <- commandArgs(trailingOnly = TRUE)
project_root <- ifelse(length(args) >= 1, args[[1]], getwd())
analysis_dir <- file.path(project_root, "Data", "analysis")
output_dir <- file.path(project_root, "Output", "tables")
notes_dir <- file.path(project_root, "Output", "empirical_notes")
dir.create(output_dir, recursive = TRUE, showWarnings = FALSE)
dir.create(notes_dir, recursive = TRUE, showWarnings = FALSE)

panel <- read_csv(
  file.path(analysis_dir, "analysis_panel_bea_summary_2016_2025_prelim.csv"),
  show_col_types = FALSE
) |>
  filter(year >= 2017, !is.na(dln_gross_output_price)) |>
  mutate(
    industry_fe = industry_code,
    shock_period = as.integer(year %in% 2021:2022),
    price_wage_gap = dln_gross_output_price - dln_avg_annual_pay,
    intermediate_wage_gap = dln_intermediate_inputs_price - dln_avg_annual_pay
  )

message("Rows: ", nrow(panel), "; industries: ", n_distinct(panel$industry_code))

m_price_full <- feols(
  dln_gross_output_price ~ network_tariff_shock_cum01 | industry_fe + year,
  cluster = ~industry_fe,
  data = panel
)

m_price_strong_links <- feols(
  dln_gross_output_price ~ network_tariff_shock_5pct_cum01 | industry_fe + year,
  cluster = ~industry_fe,
  data = panel
)

m_intermediate_full <- feols(
  dln_intermediate_inputs_price ~ network_tariff_shock_cum01 | industry_fe + year,
  cluster = ~industry_fe,
  data = panel
)

m_intermediate_strong_links <- feols(
  dln_intermediate_inputs_price ~ network_tariff_shock_5pct_cum01 | industry_fe + year,
  cluster = ~industry_fe,
  data = panel
)

m_price_wage_gap_strong_links <- feols(
  price_wage_gap ~ network_tariff_shock_5pct_cum01 | industry_fe + year,
  cluster = ~industry_fe,
  data = panel
)

m_real_wage_strong_links <- feols(
  dln_real_annual_pay_go_price ~ network_tariff_shock_5pct_cum01 | industry_fe + year,
  cluster = ~industry_fe,
  data = panel
)

m_price_shock_period <- feols(
  dln_gross_output_price ~ network_tariff_shock_cum01 * shock_period | industry_fe + year,
  cluster = ~industry_fe,
  data = panel
)

mechanism_models <- list(
  "Gross output price: full network" = m_price_full,
  "Gross output price: strong IO links" = m_price_strong_links,
  "Intermediate input price: full network" = m_intermediate_full,
  "Intermediate input price: strong IO links" = m_intermediate_strong_links,
  "Price-wage gap: strong IO links" = m_price_wage_gap_strong_links,
  "Real wage: strong IO links" = m_real_wage_strong_links,
  "Gross output price: 2021-22 interaction" = m_price_shock_period
)

sink(file.path(output_dir, "mechanism_heterogeneity_etable.txt"))
cat("Mechanism and heterogeneity TWFE models\n")
cat("Generated by Data/scripts/05_run_mechanism_heterogeneity_models.R\n")
cat("All models include BEA summary industry fixed effects and year fixed effects. Standard errors are clustered by industry.\n")
cat("The strong-link network uses the Acemoglu et al. style 5 percent input-share threshold.\n")
cat("The price-wage gap is dln_gross_output_price minus dln_avg_annual_pay; it is the negative of industry-price real wage growth when samples match.\n\n")
print(etable(mechanism_models, fitstat = ~ n + r2 + wr2))
sink()

extract_coefs <- function(model_list) {
  bind_rows(lapply(names(model_list), function(model_name) {
    ct <- coeftable(model_list[[model_name]])
    tibble(
      model = model_name,
      term = rownames(ct),
      estimate = ct[, "Estimate"],
      std_error = ct[, "Std. Error"],
      t_value = ct[, "t value"],
      p_value = ct[, "Pr(>|t|)"],
      nobs = nobs(model_list[[model_name]])
    )
  }))
}

coef_out <- extract_coefs(mechanism_models)
write_csv(coef_out, file.path(output_dir, "mechanism_heterogeneity_coefficients.csv"))

sig_lines <- coef_out |>
  mutate(significance = case_when(
    p_value < 0.01 ~ "1%",
    p_value < 0.05 ~ "5%",
    p_value < 0.10 ~ "10%",
    TRUE ~ "not significant"
  ))

note <- c(
  "# 机制与异质性检验结果备忘",
  "",
  "本表将显著性检验的重点从工资项本身转向本文理论真正要求较强的环节：关税冲击是否通过投入产出网络推高价格，尤其是通过关键供应链连接推高中间品投入价格和总产出价格。",
  "",
  "核心结果：",
  "",
  paste0(
    "- 完整 IO 网络冲击对总产出价格的影响：系数 ",
    sprintf("%.4f", sig_lines$estimate[sig_lines$model == "Gross output price: full network" & sig_lines$term == "network_tariff_shock_cum01"]),
    "，p = ",
    sprintf("%.4f", sig_lines$p_value[sig_lines$model == "Gross output price: full network" & sig_lines$term == "network_tariff_shock_cum01"]),
    "。"
  ),
  paste0(
    "- Acemoglu 5% 强连接网络冲击对总产出价格的影响：系数 ",
    sprintf("%.4f", sig_lines$estimate[sig_lines$model == "Gross output price: strong IO links" & sig_lines$term == "network_tariff_shock_5pct_cum01"]),
    "，p = ",
    sprintf("%.4f", sig_lines$p_value[sig_lines$model == "Gross output price: strong IO links" & sig_lines$term == "network_tariff_shock_5pct_cum01"]),
    "。"
  ),
  paste0(
    "- 完整 IO 网络冲击对中间品投入价格的影响：系数 ",
    sprintf("%.4f", sig_lines$estimate[sig_lines$model == "Intermediate input price: full network" & sig_lines$term == "network_tariff_shock_cum01"]),
    "，p = ",
    sprintf("%.4f", sig_lines$p_value[sig_lines$model == "Intermediate input price: full network" & sig_lines$term == "network_tariff_shock_cum01"]),
    "。"
  ),
  paste0(
    "- Acemoglu 5% 强连接网络冲击对中间品投入价格的影响：系数 ",
    sprintf("%.4f", sig_lines$estimate[sig_lines$model == "Intermediate input price: strong IO links" & sig_lines$term == "network_tariff_shock_5pct_cum01"]),
    "，p = ",
    sprintf("%.4f", sig_lines$p_value[sig_lines$model == "Intermediate input price: strong IO links" & sig_lines$term == "network_tariff_shock_5pct_cum01"]),
    "。"
  ),
  "",
  "解释：这些结果说明，显著性最强的经验事实不是工资项单独下降，而是价格冲击沿关键投入产出连接传导，并首先体现在中间品投入价格与总产出价格上。本文可以据此论证：当低价贸易品和关键供应链价格缓冲被削弱时，劳动力再生产成本面对更高价格压力；工资端没有同步补偿，因此价格型阶级妥协的物质基础受到侵蚀。",
  "",
  "写作建议：把价格和中间品投入价格结果作为主显著结果，把价格-工资缺口/实际工资下降作为方向一致的辅助证据。"
)

writeLines(note, file.path(notes_dir, "mechanism_heterogeneity_results_note.md"))

message("Wrote mechanism heterogeneity outputs.")
